In [26]:
import numpy as np
import read_data
import pandas
import os
import math
import numpy as np
import os, glob, cv2
import mediapipe as mp
import pandas
import LipLandmarks as lp
import csv
import pnn
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale

In [27]:
csv_filename = "dataset.csv"
	
if not os.path.exists(csv_filename):
	read_data.create_csv(csv_filename)

FileNotFoundError: [WinError 2] Impossibile trovare il file specificato: 'Dataset'

In [ ]:

data = read_data.create_df(csv_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'dataset.csv'

In [ ]:
data

{'x_train': array([[11.40175425,  5.83095189,  8.06225775, ..., 10.44030651,
          8.24621125,  6.40312424],
        [19.02629759, 11.66190379, 12.36931688, ..., 19.02629759,
         16.03121954, 15.62049935],
        [12.16552506,  9.21954446, 13.15294644, ..., 11.40175425,
          8.24621125,  5.83095189],
        ...,
        [ 8.        ,  3.16227766,  3.60555128, ...,  8.        ,
          6.        ,  5.38516481],
        [ 9.05538514,  4.12310563,  5.09901951, ...,  8.06225775,
          7.07106781,  6.40312424],
        [13.15294644, 10.04987562, 13.        , ..., 12.04159458,
          9.05538514,  5.83095189]]),
 'x_test': array([[11.40175425,  8.54400375, 12.04159458, ..., 11.40175425,
          8.54400375,  5.38516481],
        [20.02498439, 12.        , 16.55294536, ..., 21.02379604,
         16.03121954, 10.81665383],
        [11.40175425,  8.06225775, 10.81665383, ..., 10.44030651,
          8.24621125,  4.47213595],
        ...,
        [ 8.        ,  5.09901951

In [ ]:
predictions = pnn.PNN(data)

pnn.print_metrics(data['y_test'], predictions)

Confusion Matrix
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]
Accuracy: 0.0
Precision: 0.0
Recall: 0.0
